const players=[

// CSK
["MS Dhoni","CSK"],
["Ruturaj Gaikwad","CSK"],
["Shivam Dube","CSK"],
["Sanju Samson","CSK"],
["Rahul Chahar","CSK"],
["Sarfaraz Khan","CSK"],
["Matt Henry","CSK"],
["Akeal Hosein","CSK"],
["Noor Ahmad","CSK"],
["Mukesh Choudhary","CSK"],
["Khaleel Ahmed","CSK"],
["Nathan Ellis","CSK"],
["Jamie Overton","CSK"],
["Dewald Brevis","CSK"],
["Matthew Short","CSK"],
["Prashant Veer","CSK"],
["Kartik Sharma","CSK"],
["Aman Khan","CSK"],
["Ayush Mhatre","CSK"],
["Ramakrishna Ghosh","CSK"],


// RCB
["Virat Kohli","RCB"],
["Rajat Patidar","RCB"],
["Phil Salt","RCB"],
["Josh Hazlewood","RCB"],
["Krunal Pandya","RCB"],
["Bhuvneshwar Kumar","RCB"],
["Tim David","RCB"],
["Romario Shepherd","RCB"],
["Suyash Sharma","RCB"],
["Devdutt Padikkal","RCB"],
["Jacob Bethell","RCB"],
["Jitesh Sharma","RCB"],
["Nuwan Thushara","RCB"],
["Swapnil Singh","RCB"],
["Rasikh Dar","RCB"],
["Yash Dayal","RCB"],
["Jordan Cox","RCB"],
["Venkatesh Iyer","RCB"],
["Mangesh Yadav","RCB"],
["Vicky Ostwal","RCB"],


// MI
["Hardik Pandya","MI"],
["Rohit Sharma","MI"],
["Suryakumar Yadav","MI"],
["Jasprit Bumrah","MI"],
["Trent Boult","MI"],
["Jonny Bairstow","MI"],
["Will Jacks","MI"],
["Rovman Powell","MI"],
["Maheesh Theekshana","MI"],
["Nathan Ellis","MI"],
["Robin Minz","MI"],
["Arjun Tendulkar","MI"],
["Naman Dhir","MI"],
["Karn Sharma","MI"],
["Kumar Kushagra","MI"],
["Ashwani Kumar","MI"],


// KKR
["Ajinkya Rahane","KKR"],
["Rinku Singh","KKR"],
["Andre Russell","KKR"],
["Sunil Narine","KKR"],
["Varun Chakravarthy","KKR"],
["Cameron Green","KKR"],
["Matheesha Pathirana","KKR"],
["Rahmanullah Gurbaz","KKR"],
["Rovman Powell","KKR"],
["Manish Pandey","KKR"],
["Umran Malik","KKR"],
["Vaibhav Arora","KKR"],
["Anrich Nortje","KKR"],
["Finn Allen","KKR"],
["Mustafizur Rahman","KKR"],
["Prithvi Shaw","KKR"],
["Rahul Tripathi","KKR"],


// SRH
["Pat Cummins","SRH"],
["Sai Sudharsan","SRH"],
["Abhishek Sharma","SRH"],
["Tilak Varma","SRH"],
["Heinrich Klaasen","SRH"],
["Mitchell Marsh","SRH"],
["Mohammed Shami","SRH"],
["Harshal Patel","SRH"],
["Kamindu Mendis","SRH"],
["Abhinav Manohar","SRH"],
["Jaydev Unadkat","SRH"],
["Mujeeb Ur Rahman","SRH"],
["Rahul Chahar","SRH"],
["Aaron Hardie","SRH"],
["Spencer Johnson","SRH"],


// GT
["Shubman Gill","GT"],
["Jos Buttler","GT"],
["Ishan Kishan","GT"],
["Rashid Khan","GT"],
["Mohammed Siraj","GT"],
["Kagiso Rabada","GT"],
["Rahul Tewatia","GT"],
["Shahrukh Khan","GT"],
["Mahipal Lomror","GT"],
["Washington Sundar","GT"],
["Anuj Rawat","GT"],
["Prasidh Krishna","GT"],
["Ishant Sharma","GT"],
["Glenn Phillips","GT"],
["Sai Kishore","GT"],


// DC
["KL Rahul","DC"],
["Axar Patel","DC"],
["Mitchell Starc","DC"],
["Kuldeep Yadav","DC"],
["Tristan Stubbs","DC"],
["Abhishek Porel","DC"],
["David Miller","DC"],
["Prithvi Shaw","DC"],
["Karun Nair","DC"],
["Mukesh Kumar","DC"],
["Dushmantha Chameera","DC"],
["T Natarajan","DC"],
["Ben Duckett","DC"],
["Kyle Jamieson","DC"],
["Lungi Ngidi","DC"],


// RR
["Sanju Samson","RR"],
["Yashasvi Jaiswal","RR"],
["Riyan Parag","RR"],
["Dhruv Jurel","RR"],
["Shimron Hetmyer","RR"],
["Wanindu Hasaranga","RR"],
["Jofra Archer","RR"],
["Maheesh Theekshana","RR"],
["Sandeep Sharma","RR"],
["Akash Madhwal","RR"],
["Vaibhav Sooryavanshi","RR"],


// PBKS
["Shreyas Iyer","PBKS"],
["Marcus Stoinis","PBKS"],
["Yuzvendra Chahal","PBKS"],
["Arshdeep Singh","PBKS"],
["Marco Jansen","PBKS"],
["Prabhsimran Singh","PBKS"],
["Nehal Wadhera","PBKS"],
["Harpreet Brar","PBKS"],
["Lockie Ferguson","PBKS"],
["Vijaykumar Vyshak","PBKS"],
["Yash Thakur","PBKS"],
["Azmatullah Omarzai","PBKS"],


// LSG
["Rishabh Pant","LSG"],
["Nicholas Pooran","LSG"],
["Mitchell Marsh","LSG"],
["Aiden Markram","LSG"],
["Mayank Yadav","LSG"],
["Avesh Khan","LSG"],
["Mohsin Khan","LSG"],
["Wanindu Hasaranga","LSG"],
["Josh Inglis","LSG"],
["Arjun Tendulkar","LSG"],
["Digvesh Rathi","LSG"],
["Prince Yadav","LSG"]

]
